import { ColorPalette } from '@/types/portfolio';

export const getThemeColors = (palette: ColorPalette) => {
  const themes = {
    blue: {
      name: 'blue',
      primary: 'text-blue-400',
      bg: 'bg-blue-600',
      bgLight: 'bg-blue-50',
      border: 'border-blue-400',
      gradient: 'from-blue-500 to-indigo-500',
      button: 'bg-blue-600 hover:bg-blue-700',
      icon: 'text-blue-400',
      ring: 'ring-blue-500',
    },
    purple: {
      name: 'purple',
      primary: 'text-purple-400',
      bg: 'bg-purple-600',
      bgLight: 'bg-purple-50',
      border: 'border-purple-400',
      gradient: 'from-purple-500 to-fuchsia-500',
      button: 'bg-purple-600 hover:bg-purple-700',
      icon: 'text-purple-400',
      ring: 'ring-purple-500',
    },
    emerald: {
      name: 'emerald',
      primary: 'text-emerald-400',
      bg: 'bg-emerald-600',
      bgLight: 'bg-emerald-50',
      border: 'border-emerald-400',
      gradient: 'from-emerald-500 to-teal-500',
      button: 'bg-emerald-600 hover:bg-emerald-700',
      icon: 'text-emerald-400',
      ring: 'ring-emerald-500',
    },
    rose: {
      name: 'rose',
      primary: 'text-rose-400',
      bg: 'bg-rose-600',
      bgLight: 'bg-rose-50',
      border: 'border-rose-400',
      gradient: 'from-rose-500 to-pink-500',
      button: 'bg-rose-600 hover:bg-rose-700',
      icon: 'text-rose-400',
      ring: 'ring-rose-500',
    },
    amber: {
      name: 'amber',
      primary: 'text-amber-400',
      bg: 'bg-amber-600',
      bgLight: 'bg-amber-50',
      border: 'border-amber-400',
      gradient: 'from-amber-400 to-orange-500',
      button: 'bg-amber-600 hover:bg-amber-700',
      icon: 'text-amber-400',
      ring: 'ring-amber-500',
    },
    slate: {
      name: 'slate',
      primary: 'text-slate-300',
      bg: 'bg-slate-600',
      bgLight: 'bg-slate-100',
      border: 'border-slate-400',
      gradient: 'from-slate-400 to-slate-600',
      button: 'bg-slate-600 hover:bg-slate-700',
      icon: 'text-slate-300',
      ring: 'ring-slate-400',
    },
    cyan: {
      name: 'cyan',
      primary: 'text-cyan-400',
      bg: 'bg-cyan-600',
      bgLight: 'bg-cyan-50',
      border: 'border-cyan-400',
      gradient: 'from-cyan-400 to-blue-500',
      button: 'bg-cyan-600 hover:bg-cyan-700',
      icon: 'text-cyan-400',
      ring: 'ring-cyan-500',
    },
    indigo: {
      name: 'indigo',
      primary: 'text-indigo-400',
      bg: 'bg-indigo-600',
      bgLight: 'bg-indigo-50',
      border: 'border-indigo-400',
      gradient: 'from-indigo-500 to-purple-600',
      button: 'bg-indigo-600 hover:bg-indigo-700',
      icon: 'text-indigo-400',
      ring: 'ring-indigo-500',
    },
    orange: {
      name: 'orange',
      primary: 'text-orange-400',
      bg: 'bg-orange-600',
      bgLight: 'bg-orange-50',
      border: 'border-orange-400',
      gradient: 'from-orange-400 to-red-500',
      button: 'bg-orange-600 hover:bg-orange-700',
      icon: 'text-orange-400',
      ring: 'ring-orange-500',
    },
    teal: {
      name: 'teal',
      primary: 'text-teal-400',
      bg: 'bg-teal-600',
      bgLight: 'bg-teal-50',
      border: 'border-teal-400',
      gradient: 'from-teal-400 to-emerald-500',
      button: 'bg-teal-600 hover:bg-teal-700',
      icon: 'text-teal-400',
      ring: 'ring-teal-500',
    },
  };

  return themes[palette] || themes.blue;
};
